import { NavLink, Outlet } from 'react-router-dom';
import clsx from 'clsx';
import { Activity, BookOpen, Code2, Gauge, History, LayoutDashboard, ListOrdered, LogOut, Megaphone, ShieldCheck, Users, Wifi, WifiOff, Radio } from 'lucide-react';
import { useAuth } from '../lib/auth';
import { useLive, useNow } from '../lib/live';

export function ConnectionChip() {
  const { connection, lastMessageAt } = useLive();
  const now = useNow(1000);
  const age = lastMessageAt ? Math.max(0, Math.round((now - lastMessageAt) / 1000)) : null;
  if (connection === 'live') {
    return <span role="status" className="inline-flex items-center gap-1.5 rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-medium text-emerald-800"><Wifi className="h-3.5 w-3.5" aria-hidden />Live{age !== null && age > 45 ? ` · quiet for ${age}s` : ''}</span>;
  }
  return (
    <span role="status" className="inline-flex items-center gap-1.5 rounded-full bg-amber-100 px-2.5 py-1 text-xs font-medium text-amber-900">
      <WifiOff className="h-3.5 w-3.5" aria-hidden />{connection === 'connecting' ? 'Connecting…' : `Reconnecting — data may be stale${age !== null ? ` (last update ${age}s ago)` : ''}`}
    </span>
  );
}

const NAV = [
  { to: '/', label: 'Wallboard', icon: LayoutDashboard, end: true, roles: ['admin', 'supervisor'] },
  { to: '/agents', label: 'Agents', icon: Users, roles: ['admin', 'supervisor'] },
  { to: '/queues', label: 'Queues', icon: ListOrdered, roles: ['admin', 'supervisor'] },
  { to: '/campaigns', label: 'Campaigns', icon: Megaphone, roles: ['admin', 'supervisor'] },
  { to: '/calls', label: 'Call log', icon: History, roles: ['admin', 'supervisor'] },
  { to: '/reports', label: 'Reports', icon: Activity, roles: ['admin', 'supervisor'] },
  { to: '/developer', label: 'Developer', icon: Code2, roles: ['admin'] },
  { to: '/privacy', label: 'Privacy & compliance', icon: ShieldCheck, roles: ['admin', 'supervisor'] },
  { to: '/audit', label: 'Audit log', icon: BookOpen, roles: ['admin'] },
  { to: '/system', label: 'Platform showcase', icon: Gauge, roles: ['admin'] },
];

export function SimulationBanner() {
  const { simulated } = useLive();
  if (!simulated) return null;
  return (
    <div className="border-b border-amber-200 bg-amber-50 px-4 py-1.5 text-center text-xs text-amber-900">
      <Radio className="mr-1 inline h-3 w-3" aria-hidden /><strong>Simulated telephony.</strong> Calls, agents and carrier results on this screen are generated by the demo engine — no real PSTN calls or SMS are placed.
    </div>
  );
}

export function AdminLayout() {
  const { user, company, logout } = useAuth();
  return (
    <div className="flex min-h-screen flex-col md:flex-row">
      <a href="#main" className="sr-only focus:not-sr-only focus:absolute focus:left-2 focus:top-2 focus:z-50 focus:rounded focus:bg-white focus:px-3 focus:py-2">Skip to content</a>
      <aside className="flex shrink-0 flex-col bg-ink-900 text-slate-300 md:sticky md:top-0 md:h-screen md:w-60">
        <div className="px-4 py-4">
          <div className="text-lg font-semibold tracking-tight text-white">Swadesh<span className="text-brand-500"> CC</span></div>
          <div className="mt-0.5 truncate text-xs text-slate-400">{company?.name}</div>
        </div>
        <nav aria-label="Main" className="flex gap-1 overflow-x-auto px-2 pb-2 md:flex-1 md:flex-col md:overflow-visible">
          {NAV.filter((n) => n.roles.includes(user!.role)).map((n) => (
            <NavLink key={n.to} to={n.to} end={n.end}
              className={({ isActive }) => clsx('flex shrink-0 items-center gap-2.5 rounded-lg px-3 py-2 text-sm', isActive ? 'bg-ink-700 text-white' : 'hover:bg-ink-800 hover:text-white')}>
              <n.icon className="h-4 w-4" aria-hidden />{n.label}
            </NavLink>
          ))}
        </nav>
        <div className="hidden border-t border-ink-700 p-3 md:block">
          <div className="truncate text-sm text-white">{user?.name}</div>
          <div className="mb-2 text-xs capitalize text-slate-400">{user?.role}</div>
          <button onClick={logout} className="flex items-center gap-2 text-xs text-slate-400 hover:text-white"><LogOut className="h-3.5 w-3.5" aria-hidden />Sign out</button>
        </div>
      </aside>
      <div className="flex min-w-0 flex-1 flex-col">
        <SimulationBanner />
        <header className="flex items-center justify-between gap-3 border-b border-slate-200 bg-white px-4 py-2">
          <ConnectionChip />
          <button onClick={logout} className="text-xs text-slate-500 md:hidden">Sign out</button>
        </header>
        <main id="main" className="flex-1 p-4 md:p-6"><Outlet /></main>
      </div>
    </div>
  );
}
